<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AddRazorSupportForMvc>false</AddRazorSupportForMvc>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Yoga.Net" Version="3.2.3" />
    <PackageReference Include="HarfBuzzSharp" Version="14.2.1.102" />
    <PackageReference Include="HarfBuzzSharp.NativeAssets.macOS" Version="14.2.1.102" />
    <PackageReference Include="HarfBuzzSharp.NativeAssets.Win32" Version="14.2.1.102" />
    <PackageReference Include="HarfBuzzSharp.NativeAssets.Linux" Version="14.2.1.102" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WolfEngine\WolfEngine.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>WolfEngine.UI.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
