<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\WolfEngine\WolfEngine.csproj" />
    <ProjectReference Include="..\WolfEngine.Editor\WolfEngine.Editor.csproj" />
  </ItemGroup>
</Project>
